apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-cafeweb
  labels:
    app: cafeapp
    tier: frontend
    version: {{ .Values.cafeweb.tag }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: cafeapp
      tier: frontend
      version: {{ .Values.cafeweb.tag }}
  template:
    metadata:
      labels:
        app: cafeapp
        tier: frontend
        version: {{ .Values.cafeweb.tag }}
    spec:
      containers:
      - name: cafeweb
        image: {{ .Values.cafeweb.image }}:{{ .Values.cafeweb.tag }}
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          value: {{ .Values.config.db_url }}
        - name: DB_NAME
          value: {{ .Values.config.db_name }}
        - name: DB_USER
          value: {{ .Values.config.db_user }}
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-db-pass
              key: password
        volumeMounts:
        - name: app-config-volume
          mountPath: /var/www/html/getAppParameters.php
          subPath: getAppParameters.php
      volumes:
      - name: app-config-volume
        configMap:
          name: {{ .Release.Name }}-cafeweb-config

