apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cafeapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/thejasbp/Cafe_Dynamic_Website_Kube.git'
    targetRevision: HEAD
    path: Deploy/Helm_Chart_CafeApp
    helm:
      valueFiles:
        - values-dev.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
